In [88]:
import pandas as pd

pd.options.display.max_colwidth = 200
%matplotlib inline

In [89]:
tweets_df = pd.read_csv('data/train.csv', index_col='id')
#tweets_df_test = pd.read_csv('data/test.csv')

In [90]:
tweets_df.head()

keyword location  \
id                    
1      NaN      NaN   
4      NaN      NaN   
5      NaN      NaN   
6      NaN      NaN   
7      NaN      NaN   

                                                                                                                                     text  \
id                                                                                                                                          
1                                                                   Our Deeds are the Reason of this #earthquake May ALLAH Forgive us all   
4                                                                                                  Forest fire near La Ronge Sask. Canada   
5   All residents asked to 'shelter in place' are being notified by officers. No other evacuation or shelter in place orders are expected   
6                                                                       13,000 people receive #wildfires evacuation orders in California    
7                                                Just got sent this photo from Ruby #Alaska as smoke from #wildfires pours into a school    

    target  
id          
1        1  
4        1  
5        1  
6        1  
7        1

In [100]:
tweets_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7613 entries, 1 to 10873
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   keyword   7552 non-null   object
 1   location  5080 non-null   object
 2   text      7613 non-null   object
 3   target    7613 non-null   int64 
dtypes: int64(1), object(3)
memory usage: 297.4+ KB


In [101]:
# number of false(0:non-disaster) vs real(1:disaster) tweets
tweets_df['target'].value_counts()

0    4342
1    3271
Name: target, dtype: int64

In [92]:
# real tweets examples
tweets_df[tweets_df['target'] == 1].head()

keyword location  \
id                    
1      NaN      NaN   
4      NaN      NaN   
5      NaN      NaN   
6      NaN      NaN   
7      NaN      NaN   

                                                                                                                                     text  \
id                                                                                                                                          
1                                                                   Our Deeds are the Reason of this #earthquake May ALLAH Forgive us all   
4                                                                                                  Forest fire near La Ronge Sask. Canada   
5   All residents asked to 'shelter in place' are being notified by officers. No other evacuation or shelter in place orders are expected   
6                                                                       13,000 people receive #wildfires evacuation orders in California    
7                                                Just got sent this photo from Ruby #Alaska as smoke from #wildfires pours into a school    

    target  
id          
1        1  
4        1  
5        1  
6        1  
7        1

In [102]:
tweets_df.index

Int64Index([    1,     4,     5,     6,     7,     8,    10,    13,    14,
               15,
            ...
            10862, 10863, 10864, 10866, 10867, 10869, 10870, 10871, 10872,
            10873],
           dtype='int64', name='id', length=7613)

In [103]:
tweets_df[tweets_df.keyword.notnull()]

keyword                       location  \
id                                              
48      ablaze                     Birmingham   
49      ablaze  Est. September 2012 - Bristol   
50      ablaze                         AFRICA   
52      ablaze               Philadelphia, PA   
53      ablaze                     London, UK   
...        ...                            ...   
10830  wrecked                            NaN   
10831  wrecked              Vancouver, Canada   
10832  wrecked                        London    
10833  wrecked                        Lincoln   
10834  wrecked                            NaN   

                                                                                                              text  \
id                                                                                                                   
48                                                         @bbcmtd Wholesale Markets ablaze http://t.co/lHYXEOHY6C   
49                                             We always try to bring the heavy. #metal #RT http://t.co/YAo1e0xngw   
50                              #AFRICANBAZE: Breaking news:Nigeria flag set ablaze in Aba. http://t.co/2nndBGwyEi   
52                                                                              Crying out for more! Set me ablaze   
53                                    On plus side LOOK AT THE SKY LAST NIGHT IT WAS ABLAZE http://t.co/qqsmshaJ3N   
...                                                                                                            ...   
10830                                                             @jt_ruff23 @cameronhacker and I wrecked you both   
10831  Three days off from work and they've pretty much all been wrecked hahaha shoutout to my family for that one   
10832                #FX #forex #trading Cramer: Iger's 3 words that wrecked Disney's stock http://t.co/7enNulLKzM   
10833     @engineshed Great atmosphere at the British Lion gig tonight. Hearing is wrecked. http://t.co/oMNBAtJEAO   
10834                             Cramer: Iger's 3 words that wrecked Disney's stock - CNBC http://t.co/N6RBnHMTD4   

       target  
id             
48          1  
49          0  
50          1  
52          0  
53          0  
...       ...  
10830       0  
10831       0  
10832       0  
10833       0  
10834       0  

[7552 rows x 4 columns]

In [104]:
tweets_df.keyword.value_counts()

fatalities               45
armageddon               42
deluge                   42
harm                     41
body%20bags              41
                         ..
forest%20fire            19
epicentre                12
threat                   11
inundation               10
radiation%20emergency     9
Name: keyword, Length: 221, dtype: int64

In [105]:
X = tweets_df.text
y = tweets_df.target

In [106]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 44)

In [107]:
from sklearn.feature_extraction.text import CountVectorizer
vect = CountVectorizer(stop_words='english', max_df=0.5, min_df=2, ngram_range=(1,2))

In [108]:
vect.fit(X_train)
X_train_dtm = vect.transform(X_train)

In [109]:
X_train_dtm

<5709x9321 sparse matrix of type '<class 'numpy.int64'>'
	with 58474 stored elements in Compressed Sparse Row format>

In [110]:
X_test_dtm = vect.transform(X_test)

In [111]:
vect.get_feature_names()

['00',
 '00 11',
 '00 52',
 '00 ep',
 '00 http',
 '00 pm',
 '000',
 '000 riot',
 '01',
 '01 04',
 '01 10',
 '01 utc2015',
 '02',
 '02 scene',
 '03',
 '04',
 '04 01',
 '04 utc',
 '05',
 '05 10',
 '05 15',
 '05 16',
 '05 17',
 '05 23',
 '06',
 '06 00',
 '06 01',
 '06 2015',
 '06 http',
 '07',
 '07 00',
 '07 2015',
 '07 http',
 '08',
 '08 00',
 '08 05',
 '08 06',
 '087809233445',
 '087809233445 pin',
 '09',
 '09 utc2015',
 '0l',
 '0wratka2jl',
 '10',
 '10 00',
 '10 30',
 '10 30pm',
 '10 http',
 '10 years',
 '100',
 '100 mix',
 '1000',
 '101',
 '101 cook',
 '1023',
 '1023 spirit',
 '103',
 '106',
 '1061thetwister',
 '109',
 '109 sn',
 '10km',
 '10km maximum',
 '10th',
 '10th death',
 '11',
 '11 00',
 '11 16',
 '11 apocalypse',
 '11 charged',
 '11 new',
 '11 responders',
 '11 year',
 '12',
 '12 72w',
 '12000',
 '12000 evacuated',
 '12000 nigerian',
 '125',
 '12news',
 '12news update',
 '13',
 '13 destroyed',
 '13 reasons',
 '130',
 '130 specially',
 '13000',
 '133',
 '133 closed',
 '14',
 '

In [112]:
from sklearn.naive_bayes import MultinomialNB
nb = MultinomialNB()

In [113]:
%time
nb.fit(X_train_dtm, y_train)

Wall time: 0 ns


MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [114]:
y_pred_class = nb.predict(X_test_dtm)

In [115]:
from sklearn import metrics
metrics.accuracy_score(y_test, y_pred_class)

0.7993697478991597

In [116]:
print(len(y_train),len(y_test))

5709 1904


In [117]:
y_pred_class

array([0, 1, 0, ..., 0, 0, 0], dtype=int64)

In [118]:
metrics.confusion_matrix(y_test, y_pred_class)

array([[927, 130],
       [252, 595]], dtype=int64)

In [119]:
#false positives
X_test[(y_test == 0) & (y_pred_class == 1)]

id
4043                                                   DISASTER AVERTED: Police kill gunman with ‰Û÷hoax device‰Ûª atåÊcinema http://t.co/5NG0FzpVdS
242                                         Statistically I'm at more of risk of getting killed by a cop than I am of dying in an airplane accident.
2301       ESN :  Cilla Black died of stroke after fall in Spain: Sir Cliff revealed he was due to visit her in Spain next‰Û_ http://t.co/F7a66dIiYK
3064           Bigamist and his 'first' wife are charged in the deaths of his 'second' pregnant wife her child 8 her... http://t.co/dlAub2nVtN #news
6900                                                                                                        @CarlaChamorros HILLARY A MASS MURDERER.
                                                                            ...                                                                     
7211                                                              Rise up like a natural disaster we ta

In [77]:
vect.get_feature_names()

['00',
 '00 11',
 '00 52',
 '00 ep',
 '00 http',
 '00 pm',
 '000',
 '000 riot',
 '01',
 '01 04',
 '01 10',
 '01 utc2015',
 '02',
 '02 scene',
 '03',
 '04',
 '04 01',
 '04 utc',
 '05',
 '05 10',
 '05 15',
 '05 16',
 '05 17',
 '05 23',
 '06',
 '06 00',
 '06 01',
 '06 2015',
 '06 http',
 '07',
 '07 00',
 '07 2015',
 '07 http',
 '08',
 '08 00',
 '08 05',
 '08 06',
 '087809233445',
 '087809233445 pin',
 '09',
 '09 utc2015',
 '0l',
 '0wratka2jl',
 '10',
 '10 00',
 '10 30',
 '10 30pm',
 '10 http',
 '10 years',
 '100',
 '100 mix',
 '1000',
 '101',
 '101 cook',
 '1023',
 '1023 spirit',
 '103',
 '106',
 '1061thetwister',
 '109',
 '109 sn',
 '10km',
 '10km maximum',
 '10th',
 '10th death',
 '11',
 '11 00',
 '11 16',
 '11 apocalypse',
 '11 charged',
 '11 new',
 '11 responders',
 '11 year',
 '12',
 '12 72w',
 '12000',
 '12000 evacuated',
 '12000 nigerian',
 '125',
 '12news',
 '12news update',
 '13',
 '13 destroyed',
 '13 reasons',
 '130',
 '130 specially',
 '13000',
 '133',
 '133 closed',
 '14',
 '

In [84]:
# false negatives
X_test[(y_test == 1) & (y_pred_class == 0)]

3711                                                                               The Opposite of Love is Fear Here‰Ûªs Why\nhttp://t.co/r5bXZzhXkm
5825                                                    China's Stock Market Crash: Are There Gems In The Rubble? http://t.co/j4ggmKINEy #forbesasia
4224                    From recycling to only using non-hazardous chemicals Holland 1916 continually strives to maintain an eco-friendly existence.
7164                                                                                           the war on drugs has turned the U.S. into a WAR zone.
1798                                                                                                   @_chelsdelong12 @kendra_leigh13 I'll crash it
                                                                            ...                                                                     
988                                                 @fuckyeahcarey @BornVerified drake killing this dude a

In [120]:
y_pred_prob = nb.predict_proba(X_test_dtm)

In [121]:
y_pred_prob

array([[9.93738526e-01, 6.26147393e-03],
       [1.33272938e-01, 8.66727062e-01],
       [9.99583766e-01, 4.16234340e-04],
       ...,
       [9.87531746e-01, 1.24682544e-02],
       [9.94434873e-01, 5.56512745e-03],
       [9.99867583e-01, 1.32417272e-04]])

In [124]:
y_pred_prob = y_pred_prob[:,1]

In [125]:
metrics.roc_auc_score(y_test, y_pred_prob)

0.8450477448929329

In [126]:
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression()

In [127]:
%time
logreg.fit(X_train_dtm, y_train)

Wall time: 0 ns


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [128]:
y_pred_class = logreg.predict(X_test_dtm)

In [129]:
y_pred_prob = logreg.predict_proba(X_test_dtm)[:, 1]
y_pred_prob

array([0.19999457, 0.84511003, 0.06785975, ..., 0.26323402, 0.1633537 ,
       0.09035119])

In [130]:
# calculate accuracy
metrics.accuracy_score(y_test, y_pred_class)

0.7998949579831933

In [131]:
# calculate AUC
metrics.roc_auc_score(y_test, y_pred_prob)

0.8630521882005499